const HLS='https://stream.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g.m3u8';
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const video=document.getElementById('bgVideo');
if(window.Hls&&Hls.isSupported()){const hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.loadSource(HLS);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=HLS;video.addEventListener('loadedmetadata',()=>video.play().catch(()=>{}));}
const header=document.getElementById('header');window.addEventListener('scroll',()=>{const y=scrollY;header.style.backgroundColor=y>80?'rgba(5,7,10,.82)':'rgba(5,7,10,0)';header.style.backdropFilter=y>80?'blur(16px)':'blur(0px)';header.style.boxShadow=y>80?'0 14px 50px rgba(0,0,0,.25)':'0 0 0 rgba(0,0,0,0)';},{passive:true});
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'});closeMenu()}document.querySelectorAll('[data-scroll]').forEach(e=>e.addEventListener('click',()=>scrollToId(e.dataset.scroll)));
const menuBtn=document.getElementById('menuBtn'),menu=document.getElementById('mobileMenu'),menuIcon=document.getElementById('menuIcon');function closeMenu(){menu.classList.remove('open-panel');menu.classList.add('hidden-panel');menuBtn.setAttribute('aria-expanded','false');menuIcon.textContent='☰';document.body.style.overflow=''}menuBtn.addEventListener('click',()=>{const o=menu.classList.contains('open-panel');if(o)closeMenu();else{menu.classList.remove('hidden-panel');menu.classList.add('open-panel');menuBtn.setAttribute('aria-expanded','true');menuIcon.textContent='×';document.body.style.overflow='hidden'}});
const ids=['about','skills','projects','experience','certificates','contact'],map={about:'About',skills:'Stack',projects:'Projects',experience:'Experience',certificates:'Credentials',contact:'Contact'};const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('.nav-link').forEach(n=>{const a=n.dataset.nav===map[e.target.id];n.classList.toggle('text-white',a);n.classList.toggle('text-white/45',!a);let l=n.querySelector('.active-line');if(a&&!l){l=document.createElement('span');l.className='active-line absolute -bottom-2 left-0 right-0 h-px bg-sky-200';n.appendChild(l)}if(!a&&l)l.remove()})}),{rootMargin:'-35% 0px -50% 0px',threshold:0});ids.forEach(id=>{const e=document.getElementById(id);if(e)obs.observe(e)});
const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');ro.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach((e,i)=>{if(!e.classList.contains('show')){e.style.transitionDelay=Math.min(i*35,220)+'ms';ro.observe(e)}});
const card=document.getElementById('profileCard');setTimeout(()=>{card.classList.remove('opacity-0','translate-y-6','scale-[.92]');card.classList.add('opacity-100','translate-y-0','scale-100')},200);if(!reduced){card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${y*-4}deg) rotateY(${x*6}deg)`});card.addEventListener('mouseleave',()=>card.style.transform='perspective(1000px) rotateX(0) rotateY(0)')}
const modal=document.getElementById('certModal'),preview=document.getElementById('certPreview');document.querySelectorAll('[data-cert]').forEach(b=>b.addEventListener('click',()=>{preview.src=b.dataset.cert;modal.classList.remove('hidden');modal.classList.add('flex');document.body.style.overflow='hidden'}));function closeCert(){modal.classList.add('hidden');modal.classList.remove('flex');preview.src='';document.body.style.overflow=''}document.getElementById('certClose').addEventListener('click',closeCert);modal.addEventListener('click',e=>{if(e.target===modal)closeCert()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCert()});
